# Generated by Django 4.1.1 on 2022-10-03 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_service_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cleanup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
